export const fallbackCollections = [
  {
    id: "col-pastasusleri",
    isim: "Kişiye Özel Pasta Süsleri",
    aciklama: "1 Adet özel üretim. Doğum günü, baby shower ve nişan pastaları için 3D akrilik ve aynalı pleksi süsler.",
    kategori: "pasta-susleri",
    gorselUrl: "/images/gallery-5.webp",
    imageUrl: "/images/gallery-5.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-babyshower",
    isim: "Baby Shower & Doğum Magnetleri",
    aciklama: "25-100+ Adet hediyelik. Çok katmanlı akrilik bulut, melek ve çiçek detaylı el yapımı magnetler.",
    kategori: "babyshower",
    gorselUrl: "/images/gallery-2.webp",
    imageUrl: "/images/gallery-2.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-kombinsetler",
    isim: "Kutlama Kombin Setleri",
    aciklama: "1 Adet pasta süsü + 25/50 adet uyumlu konsept magnet. Pastanız ve hediyelikleriniz tam uyum içinde.",
    kategori: "kombin-setler",
    gorselUrl: "/images/gallery-4.webp",
    imageUrl: "/images/gallery-4.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-dugunnisan",
    isim: "Düğün & Nişan Hatıraları",
    aciklama: "Zarif kaligrafi, kurutulmuş çiçekler ve aynalı pleksi işçiliğiyle ömürlük hatıralar.",
    kategori: "dugun-nisan",
    gorselUrl: "/images/gallery-1.webp",
    imageUrl: "/images/gallery-1.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-dogumgunu",
    isim: "İlk Yaş & Doğum Günü",
    aciklama: "Miniklerin ilk yaş kutlamaları için yaş ve isim temalı neşeli 3D akrilik hatıralar.",
    kategori: "dogum-gunu",
    gorselUrl: "/images/gallery-3.webp",
    imageUrl: "/images/gallery-3.webp",
    imageType: "image",
    aktif: true,
  },
];
