export const fallbackCollections = [
  {
    id: "col-magnet",
    isim: "Magnet & Hediyelik",
    aciklama: "Min. 25 adet. Baby shower, doğum ve nişan kutlamaları için çok katmanlı 3D akrilik ve aynalı pleksi hatıra magnetleri.",
    kategori: "magnet",
    gorselUrl: "/images/gallery-2.webp",
    imageUrl: "/images/gallery-2.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-caketopper",
    isim: "Cake Topper (Pasta Süsleri)",
    aciklama: "1 Adet kişiye özel üretim. Doğum günü, ilk yaş ve nişan pastaları için 3D akrilik ve aynalı pleksi merkez süsleri.",
    kategori: "cake-topper",
    gorselUrl: "/images/gallery-5.webp",
    imageUrl: "/images/gallery-5.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-kapisusu",
    isim: "Kapı Süsü & Pano",
    aciklama: "1 Adet kişiye özel üretim. Hastane odası, bebek ve çocuk odaları için isimli 3D pleksi ve ahşap kasnak kapı süsleri.",
    kategori: "kapi-susu",
    gorselUrl: "/images/gallery-3.webp",
    imageUrl: "/images/gallery-3.webp",
    imageType: "image",
    aktif: true,
  },
  // Geriye dönük uyumluluk eşlemeleri
  {
    id: "col-pastasusleri",
    isim: "Kişiye Özel Pasta Süsleri",
    aciklama: "1 Adet özel üretim. Doğum günü, baby shower ve nişan pastaları için 3D akrilik ve aynalı pleksi süsler.",
    kategori: "pasta-susleri",
    gorselUrl: "/images/gallery-5.webp",
    imageUrl: "/images/gallery-5.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-babyshower",
    isim: "Baby Shower & Doğum Magnetleri",
    aciklama: "25-100+ Adet hediyelik. Çok katmanlı akrilik bulut, melek ve çiçek detaylı el yapımı magnetler.",
    kategori: "babyshower",
    gorselUrl: "/images/gallery-2.webp",
    imageUrl: "/images/gallery-2.webp",
    imageType: "image",
    aktif: true,
  },
  {
    id: "col-kombinsetler",
    isim: "Kutlama Kombin Setleri",
    aciklama: "1 Adet pasta süsü + 25/50 adet uyumlu konsept magnet. Pastanız ve hediyelikleriniz tam uyum içinde.",
    kategori: "kombin-setler",
    gorselUrl: "/images/gallery-4.webp",
    imageUrl: "/images/gallery-4.webp",
    imageType: "image",
    aktif: true,
  },
];
