export const fallbackCollections = [
  {
    id: "fallback-babyshower",
    isim: "Bulut Bebek Koleksiyonu",
    aciklama: "Baby shower ve yenidoğan kutlamaları için yumuşak hatlı, 3D akrilik bebek hediyelikleri.",
    kategori: "Babyshower",
    gorselUrl: "",
    aktif: true,
  },
  {
    id: "fallback-dogumgunu",
    isim: "Renkli Sayılar Koleksiyonu",
    aciklama: "Doğum günleri için yaş ve isim temalı, renkli ve neşeli akrilik anılıklar.",
    kategori: "Doğum Günü",
    gorselUrl: "",
    aktif: true,
  },
  {
    id: "fallback-disbugdayi",
    isim: "İlk Dişim Koleksiyonu",
    aciklama: "Diş buğdayı partilerine özel tasarlanmış sevimli figürlü 3D akrilik tasarımlar.",
    kategori: "Diş Buğdayı",
    gorselUrl: "",
    aktif: true,
  },
  {
    id: "fallback-dugun",
    isim: "Zarif Çiçekler Koleksiyonu",
    aciklama: "Düğün, nişan ve söz merasimleri için şık çiçek detaylı, aynalı pleksi hatıralar.",
    kategori: "Düğün & Nişan",
    gorselUrl: "",
    aktif: true,
  },
  {
    id: "fallback-yenidogan",
    isim: "Akdeniz Rüzgarı Koleksiyonu",
    aciklama: "Yeni doğan bebek tebrikleri için Akdeniz esintili, zeytin yaprağı detaylı özel pleksiler.",
    kategori: "Yenidoğan",
    gorselUrl: "",
    aktif: true,
  },
  {
    id: "fallback-mevlit",
    isim: "Mevlit Hatırası Koleksiyonu",
    aciklama: "Mevlit ve sünnet törenlerine özel, zarif kesimli 3D pleksi hediyelik anılıklar.",
    kategori: "Mevlit",
    gorselUrl: "",
    aktif: true,
  },
];
