import { Product } from "@/lib/types"

export const fallbackProducts: Product[] = [
  {
    id: "1",
    slug: "babyshower-bulut-set",
    isim: "Bulut Bebek Seti",
    koleksiyon: "",
    koleksiyonSlug: "babyshower",
    anaGorsel: "",
    ekGorseller: [],
    fiyatAraligi: "₺850 - ₺1.200",
    kisaAciklama: "Pastel tonlarda 3D akrilik bulut figürlü baby shower seti.",
    detayAciklama: "Her biri özenle işlenmiş, isim ve tarih kişiselleştirmeli premium baby shower hediyelikleri.",
    minimumAdet: 100,
    aktif: true,
  },
  {
    id: "2",
    slug: "babyshower-cicek-set",
    isim: "Çiçek Bebek Seti",
    koleksiyon: "",
    koleksiyonSlug: "babyshower",
    anaGorsel: "",
    ekGorseller: [],
    fiyatAraligi: "₺950 - ₺1.400",
    kisaAciklama: "Portakal çiçeği motifli, modern tasarım baby shower hediyeliği.",
    detayAciklama: "Taze ve modern çiçek illüstrasyonlarıyla hazırlanmış özel koleksiyon.",
    minimumAdet: 100,
    aktif: true,
  },
  {
    id: "3",
    slug: "dugun-zarif-cicek",
    isim: "Zarif Çiçekler Seti",
    koleksiyon: "",
    koleksiyonSlug: "dugun-nisan",
    anaGorsel: "",
    ekGorseller: [],
    fiyatAraligi: "₺1.100 - ₺1.600",
    kisaAciklama: "Düğün ve nişan için zarif çiçek detaylı akrilik hediyelikler.",
    detayAciklama: "Modern çiftler için özel tasarlanmış, isim ve tarih işlemeli premium nikah hatırası.",
    minimumAdet: 100,
    aktif: true,
  },
]
