import { Product } from "@/lib/types";

export const fallbackProducts: Product[] = [
  // 1. KİŞİYE ÖZEL PASTA SÜSLERİ (CAKE TOPPERS) - 1 ADET TEKİL
  {
    id: "ps-1",
    slug: "aynali-pleksi-ozel-isimli-pasta-susu",
    isim: "Aynalı Pleksi Özel İsimli Pasta Süsü",
    koleksiyon: "Kişiye Özel Pasta Süsleri",
    koleksiyonSlug: "pasta-susleri",
    anaGorsel: "/images/gallery-5.webp",
    ekGorseller: ["/images/gallery-5.webp", "/images/gallery-1.webp"],
    fiyatAraligi: "₺180 - ₺240",
    kisaAciklama: "Kişiye özel isim ve rakamla elde hazırlanan, gıda temasına uygun 3D aynalı pleksi pasta süsü.",
    detayAciklama: "Bebeğinizin veya çocuğunuzun ismiyle atölyemizde tek tek hazırlanan birinci sınıf aynalı pleksi pasta süsü. Gold, gümüş ve rose gold renk seçenekleri mevcuttur. Üretime başlamadan önce WhatsApp üzerinden dijital yerleşim taslağı onayınıza sunulur.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Kişiye Özel İsimli Pasta Süsü, Korumalı Ahşap Destekli Özel Kutulama",
    ozellikler: "3mm 1. Sınıf Akrilik Pleksi, Gıda Temasına Uygun Çubuk, 15-18 cm Genişlik"
  },
  {
    id: "ps-2",
    slug: "ilk-yas-one-akrilik-pasta-susu",
    isim: "İlk Yaş 'One' Akrilik Pasta Süsü",
    koleksiyon: "Kişiye Özel Pasta Süsleri",
    koleksiyonSlug: "pasta-susleri",
    anaGorsel: "/images/gallery-3.webp",
    ekGorseller: ["/images/gallery-3.webp", "/images/gallery-2.webp"],
    fiyatAraligi: "₺190 - ₺260",
    kisaAciklama: "1. yaş günü pastaları için çift katmanlı pastel akrilik ve aynalı kabartma 'One' pasta süsü.",
    detayAciklama: "Miniklerin ilk yaş kutlamalarına özel hazırlanan, fotoğraflarda derinlik katan çok katmanlı 3D akrilik pasta süsü. Çocuğunuzun ismi alt kaideye zarifçe işlenir.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Çift Katmanlı 'One' & İsimli Pasta Süsü",
    ozellikler: "Çift Katmanlı Akrilik, Mat Pastel + Parlak Aynalı Pleksi Kombinasyonu"
  },
  {
    id: "ps-3",
    slug: "safari-temali-3d-ahsap-pleksi-pasta-susu",
    isim: "Safari Temalı 3D Ahşap & Pleksi Pasta Süsü",
    koleksiyon: "Kişiye Özel Pasta Süsleri",
    koleksiyonSlug: "pasta-susleri",
    anaGorsel: "/images/gallery-4.webp",
    ekGorseller: ["/images/gallery-4.webp", "/images/gallery-5.webp"],
    fiyatAraligi: "₺220 - ₺290",
    kisaAciklama: "Doğal huş ahşap zemin üzerine kabartma akrilik safari figürleri ve isim detayı.",
    detayAciklama: "Safari ve orman konseptli baby shower ve doğum günü kutlamaları için en çok tercih edilen tasarımımız. Ahşabın doğallığı ile akriliğin net hatları birleşerek pastanızın merkezinde masalsı bir atmosfer yaratır.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Safari Temalı 3D Pasta Süsü",
    ozellikler: "Doğal Huş Ahşap + Renkli Akrilik Katmanlar, Özel Koruma Kutusu"
  },
  {
    id: "ps-4",
    slug: "zarif-cift-isimli-dugun-nisan-pasta-susu",
    isim: "Zarif Çift İsimli Düğün & Nişan Pasta Süsü",
    koleksiyon: "Kişiye Özel Pasta Süsleri",
    koleksiyonSlug: "pasta-susleri",
    anaGorsel: "/images/gallery-1.webp",
    ekGorseller: ["/images/gallery-1.webp", "/images/gallery-7.webp"],
    fiyatAraligi: "₺210 - ₺280",
    kisaAciklama: "Akdeniz kaligrafisiyle işlenmiş çift isimleri ve sonsuzluk amblemli nişan pasta süsü.",
    detayAciklama: "Nişan, söz ve düğün pastaları için hazırlanan zarif çift isimli tasarım. Gold ayna veya şeffaf buğulu pleksi seçenekleriyle sunulur.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Çift İsimli Özel Tasarım Pasta Süsü",
    ozellikler: "Özel Tasarım Kaligrafi, 3mm Aynalı Pleksi"
  },

  // 2. BABY SHOWER & DOĞUM MAGNETLERİ (25-100+ ADET)
  {
    id: "bm-1",
    slug: "3d-katmanli-akrilik-bulut-baby-shower-magneti",
    isim: "3D Katmanlı Akrilik Bulut Baby Shower Magneti",
    koleksiyon: "Baby Shower & Doğum",
    koleksiyonSlug: "babyshower",
    anaGorsel: "/images/gallery-5.webp",
    ekGorseller: ["/images/gallery-5.webp", "/images/gallery-2.webp"],
    fiyatAraligi: "₺45 - ₺65 / adet",
    kisaAciklama: "Bulut silüetli, altın aynalı isim aplikeli ve güçlü mıknatıslı el yapımı bebek hatırası.",
    detayAciklama: "Bebeğinizin gelişini kutlarken misafirlerinize sunabileceğiniz, ömür boyu buzdolaplarında saklanacak 3D katmanlı bulut magnet. İsim ve doğum tarihi özenle işlenir. Birebir dijital onay alınmadan kesim yapılmaz.",
    minimumAdet: 25,
    aktif: true,
    paketIcerigi: "Seçilen Adette Bulut Magnet, Güçlü Neodimyum Mıknatıs, Bireysel Şeffaf Kese",
    ozellikler: "Katmanlı Pleksi, 7.5 x 5.5 cm Ölçü, Güçlü Mıknatıs Tutuşu"
  },
  {
    id: "bm-2",
    slug: "ay-dede-yildiz-aynali-pleksi-bebek-hatirasi",
    isim: "Ay Dede & Yıldız Aynalı Pleksi Bebek Hatırası",
    koleksiyon: "Baby Shower & Doğum",
    koleksiyonSlug: "babyshower",
    anaGorsel: "/images/gallery-2.webp",
    ekGorseller: ["/images/gallery-2.webp", "/images/gallery-5.webp"],
    fiyatAraligi: "₺48 - ₺68 / adet",
    kisaAciklama: "Hilal ay ve minik sallanan yıldız detaylı, kişiye özel isimli bebek magneti.",
    detayAciklama: "Gümüş veya gold ayna pleksi zemin üzerine bebeğin ismi ve doğum tarihiyle hazırlanan, zarafetiyle dikkat çeken doğum hediyeliği.",
    minimumAdet: 25,
    aktif: true,
    paketIcerigi: "Seçilen Adette Ay & Yıldız Magnet, Bireysel Ambalaj",
    ozellikler: "Aynalı Pleksi, Hassas Lazer Kesim"
  },
  {
    id: "bm-3",
    slug: "kurutulmus-cicekli-seffaf-pleksi-dogum-hediyeligi",
    isim: "Kurutulmuş Çiçekli Şeffaf Pleksi Doğum Hediyeliği",
    koleksiyon: "Baby Shower & Doğum",
    koleksiyonSlug: "babyshower",
    anaGorsel: "/images/gallery-7.webp",
    ekGorseller: ["/images/gallery-7.webp", "/images/gallery-1.webp"],
    fiyatAraligi: "₺55 - ₺75 / adet",
    kisaAciklama: "Doğal kurutulmuş cipso çiçek buketi ve altın yaldız baskılı şeffaf akrilik magnet.",
    detayAciklama: "Akdeniz doğallığını kutlamanıza taşıyan, gerçek kurutulmuş çiçek detaylı el yapımı magnet hediyelik.",
    minimumAdet: 25,
    aktif: true,
    paketIcerigi: "Seçilen Adette Çiçekli Şeffaf Pleksi Magnet",
    ozellikler: "Gerçek Kurutulmuş Çiçek Buketi, 3mm Şeffaf Pleksi"
  },

  // 3. KUTLAMA KOMBİN SETLERİ (PASTA SÜSÜ + UYUMLU MAGNETLER)
  {
    id: "ks-1",
    slug: "bulut-temali-pasta-susu-ve-25-adet-magnet-seti",
    isim: "Bulut Temalı Pasta Süsü & 25 Adet Magnet Baby Shower Seti",
    koleksiyon: "Kutlama Kombin Setleri",
    koleksiyonSlug: "kombin-setler",
    anaGorsel: "/images/gallery-5.webp",
    ekGorseller: ["/images/gallery-5.webp", "/images/gallery-2.webp"],
    fiyatAraligi: "₺1.250 - ₺1.550",
    kisaAciklama: "Pastanızın üzerindeki özel isimli bulut süs ile davetlilere verilecek 25 magnetin tam konsept uyumu.",
    detayAciklama: "Kutlamanızda görsel bütünlük sağlayan avantajlı kombin set. 1 Adet Kişiye Özel İsimli Büyük Bulut Pasta Süsü + 25 Adet Uyumlu 3D Katmanlı Bulut Magnet içerir. Tek tek siparişe göre özel atölye indirimli paket fiyatıdır.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Özel İsimli Pasta Süsü + 25 Adet Uyumlu Konsept Magnet + Özel Kutulama",
    ozellikler: "Tam Renk ve Yazı Tipi Uyumu, Dijital Taslak Onayı, %100 Hasar Garantisi"
  },
  {
    id: "ks-2",
    slug: "safari-konsept-pasta-susu-ve-30-adet-magnet-paketi",
    isim: "Safari Konsept Pasta Süsü & 30 Adet Magnet Paketi",
    koleksiyon: "Kutlama Kombin Setleri",
    koleksiyonSlug: "kombin-setler",
    anaGorsel: "/images/gallery-4.webp",
    ekGorseller: ["/images/gallery-4.webp", "/images/gallery-3.webp"],
    fiyatAraligi: "₺1.450 - ₺1.850",
    kisaAciklama: "Ahşap & akrilik safari pasta süsü ve 30 adet uyumlu safari figürlü hediyelik magnet.",
    detayAciklama: "Baby shower veya 1. yaş safari partileri için eksiksiz kutlama seti. Pasta süsünüz ve dağıtacağınız magnetler aynı atölye masasında, aynı titizlikle hazırlanır.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet Ahşap-Pleksi Safari Pasta Süsü + 30 Adet Safari Magnet",
    ozellikler: "Huş Ahşap & Akrilik, Birebir Konsept Bütünlüğü"
  },
  {
    id: "ks-3",
    slug: "ilk-yas-one-pasta-susu-ve-25-adet-hatira-magnet-seti",
    isim: "İlk Yaş 'One' Pasta Süsü & 25 Adet Hatıra Magnet Seti",
    koleksiyon: "Kutlama Kombin Setleri",
    koleksiyonSlug: "kombin-setler",
    anaGorsel: "/images/gallery-3.webp",
    ekGorseller: ["/images/gallery-3.webp", "/images/gallery-5.webp"],
    fiyatAraligi: "₺1.300 - ₺1.650",
    kisaAciklama: "1 yaş pastasına özel 'One' süs ve davetlilere hediye edilecek 25 adet ilk yaş hatıra magneti.",
    detayAciklama: "Miniklerin ilk doğum gününü ölümsüzleştiren pasta süsü ve magnet ikilisi. Renk ve isim tasarımı WhatsApp'tan onaylatılır.",
    minimumAdet: 1,
    aktif: true,
    paketIcerigi: "1 Adet 'One' Pasta Süsü + 25 Adet İlk Yaş Magneti",
    ozellikler: "Pastel & Aynalı Pleksi Katmanlar, Özel Koruma Ambalajı"
  },

  // 4. DÜĞÜN & NİŞAN HATIRALARI (25-100+ ADET)
  {
    id: "dn-1",
    slug: "kurutulmus-cicekli-aynali-pleksi-nisan-magneti",
    isim: "Kurutulmuş Çiçekli & Aynalı Pleksi Nişan Magneti",
    koleksiyon: "Düğün & Nişan",
    koleksiyonSlug: "dugun-nisan",
    anaGorsel: "/images/gallery-1.webp",
    ekGorseller: ["/images/gallery-1.webp", "/images/gallery-7.webp"],
    fiyatAraligi: "₺60 - ₺85 / adet",
    kisaAciklama: "Akdeniz zarafetiyle tasarlanmış, aynalı pleksi ve doğal çiçek detaylı nişan hatırası.",
    detayAciklama: "Çiftlerin isimleri ve nişan tarihinin aynalı pleksi üzerine incelikle işlendiği, buzdolabında sanat eseri gibi duran davetli hediyeliği.",
    minimumAdet: 25,
    aktif: true,
    paketIcerigi: "Seçilen Adette Çiçekli Nişan Magneti",
    ozellikler: "Gold/Gümüş Ayna Pleksi, Gerçek Kurutulmuş Çiçek, Güçlü Mıknatıs"
  }
];
